# Generated by Django 3.2.4 on 2021-07-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('solution', models.TextField()),
                ('up', models.IntegerField()),
                ('down', models.IntegerField()),
            ],
        ),
    ]
